import db from "../config/sqlite.js";
import { getDeliverySettings, haversineKm } from "./deliveryPricingService.js";

const locationTime = value => value ? Date.parse(String(value).replace(" ", "T") + "Z") : NaN;
const rankedAvailableRiders = () => {
    const settings=getDeliverySettings(),now=Date.now(),shopReady=Number.isFinite(settings.shopLatitude)&&Number.isFinite(settings.shopLongitude);
    return db.prepare("SELECT * FROM riders WHERE account_status='active' AND availability_status='available'").all().map(rider=>{const updated=locationTime(rider.last_location_at),fresh=Number.isFinite(updated)&&now-updated<=600000,located=fresh&&shopReady&&Number.isFinite(Number(rider.current_latitude))&&Number.isFinite(Number(rider.current_longitude));return{rider,distance:located?haversineKm(settings.shopLatitude,settings.shopLongitude,Number(rider.current_latitude),Number(rider.current_longitude)):null};}).sort((a,b)=>(a.distance===null)-(b.distance===null)||(a.distance??Infinity)-(b.distance??Infinity)||a.rider.id-b.rider.id);
};

export const autoAssignPaidOrder=orderId=>{const id=Number(orderId);if(!Number.isInteger(id))return null;return db.transaction(()=>{const order=db.prepare("SELECT * FROM orders WHERE id=? AND fulfillment_type='delivery' AND payment_status='paid' AND auto_dispatch_eligible=1").get(id);if(!order||db.prepare("SELECT 1 FROM deliveries WHERE order_id=?").get(id))return null;const candidate=rankedAvailableRiders()[0];if(!candidate)return null;const rider=candidate.rider,fee=Number(order.delivery_fee||0);const result=db.prepare("INSERT INTO deliveries(order_id,rider_id,customer_id,delivery_status,delivery_address,customer_name,customer_phone,assigned_at,delivery_fee) VALUES(?,?,?,'assigned',?,?,?,CURRENT_TIMESTAMP,?)").run(order.id,rider.id,order.customer_id,order.delivery_address,order.customer_name,order.customer_phone,fee),deliveryId=Number(result.lastInsertRowid),proximity=candidate.distance===null?"available rider (location unavailable)":`${candidate.distance.toFixed(1)} km from shop`;db.prepare("INSERT INTO delivery_events(delivery_id,order_id,actor_type,actor_id,from_status,to_status,note) VALUES(?,?,'system',NULL,NULL,'assigned',?)").run(deliveryId,order.id,`Automatically assigned to ${rider.full_name}: ${proximity}`);db.prepare("INSERT INTO rider_notifications(rider_id,title,message,type,delivery_id) VALUES(?,'New delivery request',?,'assignment',?)").run(rider.id,`Order #${order.id} has been assigned to you.`,deliveryId);db.prepare("UPDATE riders SET availability_status='busy',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(rider.id);db.prepare("UPDATE orders SET order_status='processing',auto_dispatch_eligible=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(order.id);return{deliveryId,orderId:order.id,riderId:rider.id};})();};
export const dispatchOldestWaitingOrder=()=>{const row=db.prepare("SELECT id FROM orders o WHERE fulfillment_type='delivery' AND payment_status='paid' AND auto_dispatch_eligible=1 AND NOT EXISTS(SELECT 1 FROM deliveries d WHERE d.order_id=o.id) ORDER BY id LIMIT 1").get();return row?autoAssignPaidOrder(row.id):null;};
