import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import db from "../config/sqlite.js";
import { getDeliverySettings, haversineKm } from "../services/deliveryPricingService.js";
import { dispatchOldestWaitingOrder } from "../services/riderDispatchService.js";

const secret = () => {
    if (!process.env.JWT_SECRET && process.env.NODE_ENV === "production") throw new Error("JWT_SECRET is required in production.");
    return process.env.JWT_SECRET || "nutridust-development-secret-change-this";
};
const publicRider = r => ({ id:r.id, fullName:r.full_name, phone:r.phone, email:r.email, profilePhoto:r.profile_photo, vehicleType:r.vehicle_type, vehicleRegistrationNumber:r.vehicle_registration_number, availabilityStatus:r.availability_status, accountStatus:r.account_status, totalDeliveries:r.total_deliveries, successfulDeliveries:r.successful_deliveries, failedDeliveries:r.failed_deliveries, walletBalance:Number(r.wallet_balance||0), totalEarnings:Number(r.total_earnings||0), currentLatitude:r.current_latitude, currentLongitude:r.current_longitude, lastLocationAt:r.last_location_at });
const parseItems = value => { try { return typeof value === "string" ? JSON.parse(value) : value || []; } catch { return []; } };
const formatDelivery = r => r && ({ id:r.id, orderId:r.order_id, riderId:r.rider_id, customerName:r.customer_name, customerPhone:r.customer_phone, deliveryAddress:r.delivery_address, deliveryStatus:r.delivery_status, orderStatus:r.order_status, paymentStatus:r.payment_status, total:Number(r.total_amount||0), deliveryFee:Number(r.delivery_fee||0), items:parseItems(r.items), deliveryNote:r.delivery_note, failureReason:r.failure_reason, proofPhoto:r.proof_photo, assignedAt:r.assigned_at, acceptedAt:r.accepted_at, pickedUpAt:r.picked_up_at, outForDeliveryAt:r.out_for_delivery_at, deliveredAt:r.delivered_at, failedAt:r.failed_at, createdAt:r.created_at });
const deliverySelect = `SELECT d.*, o.items, o.total_amount, o.payment_status, o.order_status FROM deliveries d JOIN orders o ON o.id=d.order_id`;

export const riderLogin = async (req,res) => {
    try {
        const login=String(req.body?.login||req.body?.phone||req.body?.email||"").trim(), password=String(req.body?.password||"");
        if(!login||!password) return res.status(400).json({success:false,message:"Phone/email and password are required."});
        const rider=db.prepare("SELECT * FROM riders WHERE (phone=? OR lower(email)=lower(?)) AND account_status='active'").get(login,login);
        if(!rider||!(await bcrypt.compare(password,rider.password_hash))) return res.status(401).json({success:false,message:"Invalid rider credentials."});
        return res.json({success:true,token:jwt.sign({riderId:rider.id,role:"rider"},secret(),{expiresIn:"12h"}),rider:publicRider(rider)});
    } catch { return res.status(500).json({success:false,message:"Unable to sign in."}); }
};
export const getRiderMe=(req,res)=>res.json({success:true,rider:publicRider(req.rider)});
export const getRiderDashboard=(req,res)=>res.json({success:true,rider:publicRider(req.rider),deliveries:db.prepare(`${deliverySelect} WHERE d.rider_id=? ORDER BY d.id DESC`).all(req.rider.id).map(formatDelivery),notifications:db.prepare("SELECT id,title,message,type,delivery_id AS deliveryId,read_at AS readAt,created_at AS createdAt FROM rider_notifications WHERE rider_id=? ORDER BY id DESC LIMIT 20").all(req.rider.id)});
export const getRiderDeliveries=(req,res)=>{const status=String(req.query.status||"").trim();const rows=status?db.prepare(`${deliverySelect} WHERE d.rider_id=? AND d.delivery_status=? ORDER BY d.id DESC`).all(req.rider.id,status):db.prepare(`${deliverySelect} WHERE d.rider_id=? ORDER BY d.id DESC`).all(req.rider.id);return res.json({success:true,deliveries:rows.map(formatDelivery)});};

const transitions={assigned:["accepted","failed"],accepted:["picked_up","failed"],picked_up:["out_for_delivery","failed"],out_for_delivery:["delivered","failed"]};
export const updateDeliveryStatus=(req,res)=>{
    const deliveryId=Number(req.params.id),status=String(req.body?.status||"").trim().toLowerCase(),note=String(req.body?.note||"").trim().slice(0,500)||null;
    if(!Number.isInteger(deliveryId)||!["accepted","picked_up","out_for_delivery","delivered","failed"].includes(status)) return res.status(400).json({success:false,message:"Invalid delivery request."});
    try { const result=db.transaction(()=>{const d=db.prepare(`${deliverySelect} WHERE d.id=? AND d.rider_id=?`).get(deliveryId,req.rider.id);if(!d)throw Object.assign(new Error("Delivery not found."),{status:404});if(!(transitions[d.delivery_status]||[]).includes(status))throw Object.assign(new Error(`Delivery cannot move from ${d.delivery_status} to ${status}.`),{status:409});const col={accepted:"accepted_at",picked_up:"picked_up_at",out_for_delivery:"out_for_delivery_at",delivered:"delivered_at",failed:"failed_at"}[status];const orderStatus=["accepted","picked_up","failed"].includes(status)?"processing":status;db.prepare(`UPDATE deliveries SET delivery_status=?,${col}=CURRENT_TIMESTAMP,delivery_note=COALESCE(?,delivery_note),failure_reason=CASE WHEN ?='failed' THEN ? ELSE failure_reason END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(status,note,status,note,deliveryId);db.prepare("UPDATE orders SET order_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(orderStatus,d.order_id);db.prepare("INSERT INTO delivery_events(delivery_id,order_id,actor_type,actor_id,from_status,to_status,note) VALUES(?,?,'rider',?,?,?,?)").run(deliveryId,d.order_id,req.rider.id,d.delivery_status,status,note);if(status==="delivered"){db.prepare("INSERT OR IGNORE INTO rider_earnings(rider_id,delivery_id,amount,description) VALUES(?,?,?,?)").run(req.rider.id,deliveryId,d.delivery_fee,`Delivery #${deliveryId}`);db.prepare("UPDATE riders SET availability_status='available',total_deliveries=total_deliveries+1,successful_deliveries=successful_deliveries+1,wallet_balance=wallet_balance+?,total_earnings=total_earnings+?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(d.delivery_fee,d.delivery_fee,req.rider.id);}else if(status==="failed")db.prepare("UPDATE riders SET availability_status='available',total_deliveries=total_deliveries+1,failed_deliveries=failed_deliveries+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.rider.id);else db.prepare("UPDATE riders SET availability_status='busy',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.rider.id);return db.prepare(`${deliverySelect} WHERE d.id=?`).get(deliveryId);})();return res.json({success:true,delivery:formatDelivery(result)});}catch(error){return res.status(error.status||500).json({success:false,message:error.status?error.message:"Unable to update delivery."});}
};
export const updateAvailability=(req,res)=>{const status=String(req.body?.status||"").trim().toLowerCase();if(!["available","offline"].includes(status))return res.status(400).json({success:false,message:"Status must be available or offline."});const active=db.prepare("SELECT 1 FROM deliveries WHERE rider_id=? AND delivery_status IN ('assigned','accepted','picked_up','out_for_delivery')").get(req.rider.id);if(active&&status==="offline")return res.status(409).json({success:false,message:"Complete your active delivery before going offline."});db.prepare("UPDATE riders SET availability_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,req.rider.id);if(status==="available")dispatchOldestWaitingOrder();const updated=db.prepare("SELECT availability_status FROM riders WHERE id=?").get(req.rider.id);return res.json({success:true,availabilityStatus:updated.availability_status});};
export const updateLocation=(req,res)=>{const lat=Number(req.body?.latitude),lng=Number(req.body?.longitude),accuracy=Number(req.body?.accuracy||0),deliveryId=req.body?.deliveryId?Number(req.body.deliveryId):null;if(!Number.isFinite(lat)||lat < -90||lat > 90||!Number.isFinite(lng)||lng < -180||lng > 180)return res.status(400).json({success:false,message:"Valid coordinates are required."});if(deliveryId&&!db.prepare("SELECT 1 FROM deliveries WHERE id=? AND rider_id=?").get(deliveryId,req.rider.id))return res.status(403).json({success:false,message:"Delivery does not belong to this rider."});db.transaction(()=>{db.prepare("INSERT INTO rider_locations(rider_id,delivery_id,latitude,longitude,accuracy) VALUES(?,?,?,?,?)").run(req.rider.id,deliveryId,lat,lng,accuracy||null);db.prepare("UPDATE riders SET current_latitude=?,current_longitude=?,last_location_at=CURRENT_TIMESTAMP WHERE id=?").run(lat,lng,req.rider.id);})();return res.json({success:true});};
export const getRiderEarnings=(req,res)=>res.json({success:true,balance:Number(req.rider.wallet_balance||0),totalEarnings:Number(req.rider.total_earnings||0),entries:db.prepare("SELECT id,delivery_id AS deliveryId,amount,status,description,created_at AS createdAt FROM rider_earnings WHERE rider_id=? ORDER BY id DESC").all(req.rider.id)});
export const markNotificationsRead=(req,res)=>{db.prepare("UPDATE rider_notifications SET read_at=CURRENT_TIMESTAMP WHERE rider_id=? AND read_at IS NULL").run(req.rider.id);return res.json({success:true});};
export const getAdminRiders=(req,res)=>{const settings=getDeliverySettings(),now=Date.now();const riders=db.prepare("SELECT * FROM riders ORDER BY id DESC").all().map(row=>{const rider=publicRider(row),updated=row.last_location_at?Date.parse(String(row.last_location_at).replace(" ","T")+"Z"):NaN,locationFresh=Number.isFinite(updated)&&now-updated<=10*60*1000,hasShop=Number.isFinite(settings.shopLatitude)&&Number.isFinite(settings.shopLongitude),hasRider=Number.isFinite(Number(row.current_latitude))&&Number.isFinite(Number(row.current_longitude));const distanceKm=locationFresh&&hasShop&&hasRider?haversineKm(settings.shopLatitude,settings.shopLongitude,Number(row.current_latitude),Number(row.current_longitude)):null;return {...rider,distanceToShopKm:distanceKm===null?null:Number(distanceKm.toFixed(2)),locationFresh};}).sort((a,b)=>{const rank=r=>r.accountStatus==="active"&&r.availabilityStatus==="available"&&r.locationFresh&&r.distanceToShopKm!==null?0:1;return rank(a)-rank(b)||(a.distanceToShopKm??Infinity)-(b.distanceToShopKm??Infinity);});return res.json({success:true,riders,shopLocationConfigured:Number.isFinite(settings.shopLatitude)&&Number.isFinite(settings.shopLongitude)});};
export const createAdminRider=async(req,res)=>{const{fullName,phone,email,password,vehicleType,vehicleRegistrationNumber}=req.body||{};if(!fullName||!phone||!password||String(password).length<8)return res.status(400).json({success:false,message:"Full name, phone and a password of at least 8 characters are required."});try{const hash=await bcrypt.hash(String(password),12);const result=db.prepare("INSERT INTO riders(full_name,phone,email,password_hash,vehicle_type,vehicle_registration_number) VALUES(?,?,?,?,?,?)").run(String(fullName).trim(),String(phone).trim(),email?String(email).trim().toLowerCase():null,hash,vehicleType||null,vehicleRegistrationNumber||null);return res.status(201).json({success:true,rider:publicRider(db.prepare("SELECT * FROM riders WHERE id=?").get(result.lastInsertRowid))});}catch(error){const conflict=String(error.code).includes("CONSTRAINT");return res.status(conflict?409:500).json({success:false,message:conflict?"Rider phone or email already exists.":"Unable to create rider."});}};
export const updateAdminRider=(req,res)=>{const id=Number(req.params.id),status=String(req.body?.accountStatus||"").trim().toLowerCase();if(!["active","inactive"].includes(status))return res.status(400).json({success:false,message:"Account status must be active or inactive."});const result=db.prepare("UPDATE riders SET account_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,id);return result.changes?res.json({success:true}):res.status(404).json({success:false,message:"Rider not found."});};
export const assignDelivery=(req,res)=>{const orderId=Number(req.params.orderId),riderId=Number(req.body?.riderId);if(!Number.isInteger(orderId)||!Number.isInteger(riderId))return res.status(400).json({success:false,message:"Valid order and rider are required."});try{const delivery=db.transaction(()=>{const order=db.prepare("SELECT * FROM orders WHERE id=?").get(orderId),rider=db.prepare("SELECT * FROM riders WHERE id=? AND account_status='active'").get(riderId);if(!order)throw Object.assign(new Error("Order not found."),{status:404});if(!rider)throw Object.assign(new Error("Active rider not found."),{status:404});if(rider.availability_status!=="available")throw Object.assign(new Error("Choose an available rider."),{status:409});if(!(Number(order.delivery_fee)>0))throw Object.assign(new Error("This order has no calculated delivery fare."),{status:409});if(["delivered","cancelled"].includes(order.order_status))throw Object.assign(new Error("This order cannot be assigned."),{status:409});const fee=Number(order.delivery_fee),existing=db.prepare("SELECT * FROM deliveries WHERE order_id=?").get(orderId);let id;if(existing){if(["accepted","picked_up","out_for_delivery"].includes(existing.delivery_status))throw Object.assign(new Error("An active delivery cannot be reassigned."),{status:409});db.prepare("UPDATE deliveries SET rider_id=?,delivery_status='assigned',delivery_fee=?,assigned_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(riderId,fee,existing.id);id=existing.id;}else id=Number(db.prepare("INSERT INTO deliveries(order_id,rider_id,customer_id,delivery_status,delivery_address,customer_name,customer_phone,assigned_at,delivery_fee) VALUES(?,?,?,'assigned',?,?,?,CURRENT_TIMESTAMP,?)").run(orderId,riderId,order.customer_id,order.delivery_address,order.customer_name,order.customer_phone,fee).lastInsertRowid);db.prepare("INSERT INTO delivery_events(delivery_id,order_id,actor_type,actor_id,from_status,to_status,note) VALUES(?,?,'admin',NULL,?,'assigned',?)").run(id,orderId,existing?.delivery_status||null,`Assigned to ${rider.full_name}; fare locked from order`);db.prepare("INSERT INTO rider_notifications(rider_id,title,message,type,delivery_id) VALUES(?,'New delivery assigned',?,'assignment',?)").run(riderId,`Order #${orderId} is ready for you.`,id);db.prepare("UPDATE riders SET availability_status='busy',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(riderId);db.prepare("UPDATE orders SET order_status='processing',auto_dispatch_eligible=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(orderId);return db.prepare(`${deliverySelect} WHERE d.id=?`).get(id);})();return res.status(201).json({success:true,delivery:formatDelivery(delivery)});}catch(error){return res.status(error.status||500).json({success:false,message:error.status?error.message:"Unable to assign delivery."});}};
