import express from "express";
import { adminAuth, requirePermission } from "../middleware/adminAuth.js";
import { listStaff, createStaff, updateStaffStatus, updateStaffPermissions } from "../controllers/adminStaffController.js";
const router = express.Router();
router.use(adminAuth, requirePermission("staff.manage"));
router.get("/", listStaff);
router.post("/", createStaff);
router.patch("/:id/status", updateStaffStatus);
router.patch("/:id/permissions", updateStaffPermissions);
export default router;
