import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";

const directory=await mkdtemp(join(tmpdir(),"nutridust-rider-"));
process.env.SQLITE_PATH=join(directory,"test.db");
process.env.JWT_SECRET="test-secret-that-is-long-and-isolated";
process.env.NODE_ENV="test";
const {default:db}=await import("../config/sqlite.js");
const {default:app}=await import("../app.js");
const password="SecurePass123";
const hash=await bcrypt.hash(password,4);
const customerId=Number(db.prepare("INSERT INTO customers(name,email,phone,password_hash) VALUES('Test Customer','customer@example.com','08000000001',?)").run(hash).lastInsertRowid);
const riderId=Number(db.prepare("INSERT INTO riders(full_name,phone,email,password_hash,vehicle_type) VALUES('Test Rider','08000000002','rider@example.com',?,'Bike')").run(hash).lastInsertRowid);
const orderId=Number(db.prepare("INSERT INTO orders(customer_id,customer_name,customer_phone,customer_email,delivery_address,items,total_amount,payment_status,order_status,delivery_fee) VALUES(?,'Test Customer','08000000001','customer@example.com','1 Test Street',?,5000,'paid','processing',750)").run(customerId,JSON.stringify([{productId:1,name:'Food',quantity:1}])).lastInsertRowid);
const server=app.listen(0);
const base=`http://127.0.0.1:${server.address().port}/api`;
const request=async(path,options={})=>{const response=await fetch(base+path,{...options,headers:{"content-type":"application/json",...(options.headers||{})}});return {status:response.status,body:await response.json()};};
let riderToken;

test("admin authorization rejects non-admin JWT",async()=>{const token=jwt.sign({customerId,role:"customer"},process.env.JWT_SECRET);const result=await request("/admin/riders",{headers:{authorization:`Bearer ${token}`}});assert.equal(result.status,403);});
test("staff login enforces assigned task permissions",async()=>{const staffHash=await bcrypt.hash(password,4);db.prepare("INSERT INTO staff_users(full_name,username,password_hash,role,permissions) VALUES('Order Clerk','orderclerk',?,'staff',?)").run(staffHash,JSON.stringify(["orders.view"]));let result=await request("/admin/login",{method:"POST",body:JSON.stringify({username:"orderclerk",password})});assert.equal(result.status,200,JSON.stringify(result.body));assert.deepEqual(result.body.admin.permissions,["orders.view"]);const token=result.body.token;result=await request("/admin/orders",{headers:{authorization:`Bearer ${token}`}});assert.equal(result.status,200,JSON.stringify(result.body));result=await request(`/admin/orders/${orderId}/status`,{method:"PATCH",headers:{authorization:`Bearer ${token}`},body:JSON.stringify({status:"processing"})});assert.equal(result.status,403);result=await request("/admin/staff",{headers:{authorization:`Bearer ${token}`}});assert.equal(result.status,403);});
test("pickup has no delivery charge and cannot be assigned",async()=>{const productId=Number(db.prepare("INSERT INTO products(name,category,description,image,price) VALUES('Pickup Product','Food','Test','test.png',2000)").run().lastInsertRowid);db.prepare("INSERT INTO inventory(product_id,quantity_available,reserved_quantity) VALUES(?,10,0)").run(productId);const customerToken=jwt.sign({customerId,role:"customer"},process.env.JWT_SECRET);let result=await request("/orders",{method:"POST",headers:{authorization:`Bearer ${customerToken}`},body:JSON.stringify({fulfillmentType:"pickup",items:[{productId,quantity:1}]})});assert.equal(result.status,201,JSON.stringify(result.body));const pickup=db.prepare("SELECT * FROM orders WHERE id=?").get(result.body.order.id);assert.equal(pickup.fulfillment_type,"pickup");assert.equal(pickup.delivery_fee,0);assert.equal(pickup.total_amount,2000);const admin=jwt.sign({role:"admin"},process.env.JWT_SECRET);result=await request(`/admin/riders/assign/${pickup.id}`,{method:"POST",headers:{authorization:`Bearer ${admin}`},body:JSON.stringify({riderId,deliveryFee:750})});assert.equal(result.status,409);assert.equal(db.prepare("SELECT count(*) AS count FROM deliveries WHERE order_id=?").get(pickup.id).count,0);result=await request("/orders",{method:"POST",headers:{authorization:`Bearer ${customerToken}`},body:JSON.stringify({fulfillmentType:"delivery",deliveryAddress:"2 Delivery Road",items:[{productId,quantity:1}]})});assert.equal(result.status,201,JSON.stringify(result.body));const deliveryOrder=db.prepare("SELECT * FROM orders WHERE id=?").get(result.body.order.id);assert.equal(deliveryOrder.fulfillment_type,"delivery");assert.equal(deliveryOrder.delivery_fee,1500);assert.equal(deliveryOrder.total_amount,3500);});
test("complete assignment and delivery lifecycle",async()=>{const admin=jwt.sign({role:"admin"},process.env.JWT_SECRET);let result=await request(`/admin/riders/assign/${orderId}`,{method:"POST",headers:{authorization:`Bearer ${admin}`},body:JSON.stringify({riderId,deliveryFee:750})});assert.equal(result.status,201);const deliveryId=result.body.delivery.id;result=await request("/rider/login",{method:"POST",body:JSON.stringify({login:"08000000002",password})});assert.equal(result.status,200);riderToken=result.body.token;for(const status of ["accepted","picked_up","out_for_delivery","delivered"]){result=await request(`/rider/deliveries/${deliveryId}/status`,{method:"PATCH",headers:{authorization:`Bearer ${riderToken}`},body:JSON.stringify({status})});assert.equal(result.status,200,JSON.stringify(result.body));}const row=db.prepare("SELECT wallet_balance,successful_deliveries FROM riders WHERE id=?").get(riderId);assert.equal(row.wallet_balance,750);assert.equal(row.successful_deliveries,1);assert.equal(db.prepare("SELECT order_status FROM orders WHERE id=?").get(orderId).order_status,"delivered");});

test("subscription, referral reward, and withdrawal refund are transactional",async()=>{let result=await request("/rider/commerce",{headers:{authorization:`Bearer ${riderToken}`}});assert.equal(result.status,200);assert.ok(result.body.referralCode);const planId=result.body.plans[0].id;result=await request("/rider/subscriptions",{method:"POST",headers:{authorization:`Bearer ${riderToken}`},body:JSON.stringify({planId})});assert.equal(result.status,201);const secondId=Number(db.prepare("INSERT INTO riders(full_name,phone,email,password_hash) VALUES('Second Rider','08000000003','second@example.com',?)").run(hash).lastInsertRowid);const secondToken=jwt.sign({riderId:secondId,role:"rider"},process.env.JWT_SECRET);result=await request("/rider/referrals/apply",{method:"POST",headers:{authorization:`Bearer ${secondToken}`},body:JSON.stringify({code:(await request('/rider/commerce',{headers:{authorization:`Bearer ${riderToken}`}})).body.referralCode})});assert.equal(result.status,200);db.prepare("UPDATE riders SET successful_deliveries=1 WHERE id=?").run(secondId);assert.equal(db.prepare("SELECT wallet_balance FROM riders WHERE id=?").get(riderId).wallet_balance,1250);result=await request("/rider/withdrawals",{method:"POST",headers:{authorization:`Bearer ${riderToken}`},body:JSON.stringify({amount:1000,bankName:"Test Bank",accountName:"Test Rider",accountNumber:"0123456789"})});assert.equal(result.status,201);const withdrawalId=result.body.withdrawal.id;assert.equal(db.prepare("SELECT wallet_balance FROM riders WHERE id=?").get(riderId).wallet_balance,250);const admin=jwt.sign({role:"admin"},process.env.JWT_SECRET);result=await request(`/admin/riders/withdrawals/${withdrawalId}`,{method:"PATCH",headers:{authorization:`Bearer ${admin}`},body:JSON.stringify({status:"rejected",note:"Test refund"})});assert.equal(result.status,200);assert.equal(db.prepare("SELECT wallet_balance FROM riders WHERE id=?").get(riderId).wallet_balance,1250);});

test("rider self-application requires verification and inspection before onboarding",async()=>{const form=new FormData();for(const [key,value] of Object.entries({firstName:"Ada",middleName:"Ngozi",surname:"Okafor",phone:"08000000999",email:"ada.rider@example.com",plateNumber:"LAG-123-XY",vehicleType:"Motorcycle"}))form.append(key,value);form.append("ownershipDocument",new Blob(["test proof"],{type:"application/pdf"}),"ownership.pdf");let response=await fetch(base+"/rider/applications",{method:"POST",body:form});let body=await response.json();assert.equal(response.status,201,JSON.stringify(body));assert.ok(body.verificationToken);const applicationId=body.applicationId;let result=await request("/rider/applications/verify",{method:"POST",body:JSON.stringify({token:body.verificationToken})});assert.equal(result.status,200,JSON.stringify(result.body));const admin=jwt.sign({role:"admin",username:"owner"},process.env.JWT_SECRET);result=await request(`/admin/riders/applications/${applicationId}/approve`,{method:"POST",headers:{authorization:`Bearer ${admin}`},body:"{}"});assert.equal(result.status,409);result=await request(`/admin/riders/applications/${applicationId}/inspection`,{method:"PATCH",headers:{authorization:`Bearer ${admin}`},body:JSON.stringify({inspectionStatus:"passed",inspectionNotes:"Bike inspected and fit"})});assert.equal(result.status,200,JSON.stringify(result.body));result=await request(`/admin/riders/applications/${applicationId}/approve`,{method:"POST",headers:{authorization:`Bearer ${admin}`},body:"{}"});assert.equal(result.status,201,JSON.stringify(result.body));const credentials=result.body.credentials;result=await request("/rider/login",{method:"POST",body:JSON.stringify({login:credentials.username,password:credentials.temporaryPassword})});assert.equal(result.status,200,JSON.stringify(result.body));assert.equal(result.body.rider.mustChangePassword,true);const token=result.body.token;result=await request("/rider/password/change",{method:"POST",headers:{authorization:`Bearer ${token}`},body:JSON.stringify({newPassword:"NewSecurePass456"})});assert.equal(result.status,200,JSON.stringify(result.body));result=await request("/rider/login",{method:"POST",body:JSON.stringify({login:credentials.username,password:"NewSecurePass456"})});assert.equal(result.status,200);assert.equal(result.body.rider.mustChangePassword,false);});

test("inventory exports produce real Excel and PDF files",async()=>{const admin=jwt.sign({role:"admin"},process.env.JWT_SECRET);for(const [path,signature,name] of [["/admin/inventory/reports/excel","PK","inventory-preview.xlsx"],["/admin/inventory/reports/pdf","%PDF","inventory-preview.pdf"]]){const response=await fetch(base+path,{headers:{authorization:`Bearer ${admin}`}});assert.equal(response.status,200);const bytes=new Uint8Array(await response.arrayBuffer());assert.equal(new TextDecoder().decode(bytes.slice(0,4)).startsWith(signature),true);assert.ok(bytes.length>500);if(process.env.EXPORT_PREVIEW_DIR){await mkdir(process.env.EXPORT_PREVIEW_DIR,{recursive:true});await writeFile(join(process.env.EXPORT_PREVIEW_DIR,name),bytes);}}});

test("operations automation assigns paid delivery orders only when explicitly enabled",async()=>{const automaticOrder=Number(db.prepare("INSERT INTO orders(customer_id,customer_name,customer_phone,customer_email,delivery_address,items,total_amount,payment_status,order_status,fulfillment_type) VALUES(?,'Auto Customer','08000000004','auto@example.com','4 Auto Road','[]',5000,'paid','processing','delivery')").run(customerId).lastInsertRowid);db.prepare("UPDATE riders SET availability_status='available' WHERE id=?").run(riderId);const admin=jwt.sign({role:"admin"},process.env.JWT_SECRET);const previous=process.env.AUTO_ASSIGN_RIDERS;process.env.AUTO_ASSIGN_RIDERS="true";try{const result=await request("/admin/operations/run",{method:"POST",headers:{authorization:`Bearer ${admin}`},body:"{}"});assert.equal(result.status,200);assert.ok(db.prepare("SELECT id FROM deliveries WHERE order_id=?").get(automaticOrder));}finally{if(previous===undefined)delete process.env.AUTO_ASSIGN_RIDERS;else process.env.AUTO_ASSIGN_RIDERS=previous;}});

test.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();await rm(directory,{recursive:true,force:true});});
