import axios from "axios";

const API=axios.create({baseURL:__API_URL__});
const auth=()=>({headers:{Authorization:`Bearer ${localStorage.getItem("nutridust-admin-token")}`}});
const safe=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

export function AdminRiders(){return `<section class="container-fluid px-lg-5 pb-5"><div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h4 mb-1">Rider operations</h2><p class="text-secondary mb-0">Riders are ranked by their latest distance to the shop. Delivery fare is calculated at checkout and cannot be changed here.</p></div><button id="refreshRiders" class="btn btn-outline-dark"><i class="bi bi-arrow-clockwise"></i></button></div><div id="riderAdminMessage"></div><form id="assignRiderForm" class="row g-2 p-3 rounded bg-light mb-4"><div class="col-md-4"><input name="orderId" type="number" min="1" class="form-control" placeholder="Order number" required></div><div class="col-md-6"><select name="riderId" id="assignmentRider" class="form-select" required><option value="">Select nearest available rider</option></select></div><div class="col-md-2"><button class="btn btn-success w-100">Assign</button></div></form><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Rider</th><th>Vehicle</th><th>Availability</th><th>Distance to shop</th><th>Deliveries</th><th>Earnings</th><th>Account</th></tr></thead><tbody id="riderRows"><tr><td colspan="7">Loading…</td></tr></tbody></table></div></div></div></section>`;}

export async function setupAdminRiders(){const message=document.getElementById("riderAdminMessage"),rows=document.getElementById("riderRows"),select=document.getElementById("assignmentRider"),form=document.getElementById("assignRiderForm"),distance=r=>r.distanceToShopKm===null?(r.locationFresh?"Shop location unavailable":"Location unavailable"):`${Number(r.distanceToShopKm).toFixed(1)} km away`;const load=async()=>{try{const{data}=await API.get("/admin/riders",auth());const riders=data.riders||[],eligible=riders.filter(r=>r.accountStatus==="active"&&r.availabilityStatus==="available"),options='<option value="">Select nearest available rider</option>'+eligible.map((r,index)=>`<option value="${r.id}">${index===0&&r.distanceToShopKm!==null?"Nearest — ":""}${safe(r.fullName)} — ${safe(distance(r))}</option>`).join(""),html=riders.map((r,index)=>`<tr><td><strong>${safe(r.fullName)}</strong><br><small>${safe(r.phone)}</small></td><td>${safe(r.vehicleType||"—")}<br><small>${safe(r.vehicleRegistrationNumber||"")}</small></td><td><span class="badge text-bg-${r.availabilityStatus==="available"?"success":r.availabilityStatus==="busy"?"warning":"secondary"}">${safe(r.availabilityStatus)}</span></td><td>${index===0&&r.distanceToShopKm!==null?'<span class="badge text-bg-success me-1">Nearest</span>':""}${safe(distance(r))}</td><td>${r.successfulDeliveries}/${r.totalDeliveries}</td><td>₦${Number(r.totalEarnings||0).toLocaleString()}</td><td><button class="btn btn-sm btn-outline-${r.accountStatus==="active"?"danger":"success"} rider-status" data-id="${r.id}" data-status="${r.accountStatus==="active"?"inactive":"active"}">${r.accountStatus==="active"?"Suspend":"Activate"}</button></td></tr>`).join("")||'<tr><td colspan="7">No riders created yet.</td></tr>';if(document.activeElement!==select&&select.innerHTML!==options)select.innerHTML=options;if(rows.innerHTML!==html){rows.innerHTML=html;document.querySelectorAll(".rider-status").forEach(button=>button.onclick=async()=>{await API.patch(`/admin/riders/${button.dataset.id}/status`,{accountStatus:button.dataset.status},auth());await load();});}}catch(error){rows.innerHTML=`<tr><td colspan="7" class="text-danger">${safe(error.response?.data?.message||"Unable to load riders.")}</td></tr>`;}};form?.addEventListener("submit",async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));try{await API.post(`/admin/riders/assign/${values.orderId}`,{riderId:Number(values.riderId)},auth());message.innerHTML='<div class="alert alert-success">Delivery assigned using the order’s calculated fare.</div>';form.reset();await load();}catch(error){message.innerHTML=`<div class="alert alert-danger">${safe(error.response?.data?.message||"Unable to assign delivery.")}</div>`;}});document.getElementById("refreshRiders")?.addEventListener("click",load);window.addEventListener("nutridust:admin-refresh",event=>{if(event.detail?.view==="riders")load();});await load();}
