import axios from "axios";
const API=axios.create({baseURL:__API_URL__});
const auth=()=>({headers:{Authorization:`Bearer ${localStorage.getItem("nutridust-admin-token")}`}});
const safe=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

export function AdminRiders(){return `<section class="admin-riders-view">
 <header class="rider-page-header"><div><span class="admin-eyebrow">Fleet operations</span><h1>Rider management</h1><p>Review applications, assign deliveries and monitor riders in real time.</p></div><button id="refreshRiders" class="admin-icon-button" aria-label="Refresh riders"><i class="bi bi-arrow-clockwise"></i></button></header>
 <div class="rider-kpi-grid" aria-label="Rider summary">
  <article><i class="bi bi-people"></i><div><span>Active riders</span><strong id="riderStatActive">—</strong><small>Approved accounts</small></div></article>
  <article><i class="bi bi-broadcast-pin"></i><div><span>Available now</span><strong id="riderStatAvailable">—</strong><small>Ready for orders</small></div></article>
  <article><i class="bi bi-bicycle"></i><div><span>Busy riders</span><strong id="riderStatBusy">—</strong><small>On active work</small></div></article>
  <article><i class="bi bi-file-earmark-person"></i><div><span>Applications</span><strong id="riderStatApplications">—</strong><small>Awaiting review</small></div></article>
 </div>
 <div class="admin-section-tabs" role="tablist"><button type="button" class="admin-section-tab active" data-rider-panel="operations">Active riders &amp; delivery</button><button type="button" class="admin-section-tab" data-rider-panel="applications">Applications</button></div>
 <div id="riderAdminMessage"></div>
 <div class="rider-panel" data-rider-view="operations"><div class="rider-operations-grid">
  <section class="rider-fleet-card"><div class="panel-heading"><div><h2>Active rider operations</h2><p>Live availability, distance and delivery performance.</p></div><span class="live-pill"><i></i> Auto-refresh</span></div><div class="table-responsive admin-records-scroll"><table class="table align-middle"><thead><tr><th>Rider</th><th>Vehicle</th><th>Availability</th><th>Distance to shop</th><th>Deliveries</th><th>Earnings</th><th>Account</th></tr></thead><tbody id="riderRows"><tr><td colspan="7">Loading…</td></tr></tbody></table></div></section>
  <aside class="rider-control-column">
   <form id="assignRiderForm" class="rider-tool-card rider-assignment-card"><div class="rider-tool-title"><i class="bi bi-send"></i><div><span>Assign a delivery</span><small>Enter an order to find the nearest available rider</small></div></div><label class="form-label" for="assignmentOrderId">Order number</label><input id="assignmentOrderId" name="orderId" type="number" min="1" class="form-control" placeholder="e.g. 74" autocomplete="off" required><div id="assignmentOrderFeedback" class="rider-assignment-feedback">Enter the customer order number to load available riders.</div><div id="assignmentCandidateBlock" hidden><label class="form-label" for="assignmentRider">Available riders, nearest first</label><select name="riderId" id="assignmentRider" class="form-select" required disabled><option value="">Select an available rider</option></select><small class="rider-distance-note"><i class="bi bi-geo-alt"></i> Distance is calculated from the NutriDust pickup location using each rider's latest GPS.</small></div><button id="assignDeliveryButton" class="btn btn-success" disabled><i class="bi bi-send me-1"></i>Assign delivery</button></form>
  </aside>
 </div></div>
 <div class="rider-panel" data-rider-view="applications" hidden><section class="rider-applications-card"><div class="panel-heading"><div><h2>Rider applications</h2><p>Verify submitted documents before onboarding a rider.</p></div></div><div id="applicationReview"></div><div class="table-responsive admin-records-scroll"><table class="table align-middle"><thead><tr><th>Applicant</th><th>Vehicle</th><th>Email</th><th>Inspection</th><th>Status</th><th>Action</th></tr></thead><tbody id="applicationRows"><tr><td colspan="6">Loading…</td></tr></tbody></table></div></section></div>
</section>`;}

export async function setupAdminRiders(){
 const message=document.getElementById("riderAdminMessage"),rows=document.getElementById("riderRows"),applicationRows=document.getElementById("applicationRows"),review=document.getElementById("applicationReview"),select=document.getElementById("assignmentRider"),form=document.getElementById("assignRiderForm"),orderInput=document.getElementById("assignmentOrderId"),candidateBlock=document.getElementById("assignmentCandidateBlock"),orderFeedback=document.getElementById("assignmentOrderFeedback"),assignButton=document.getElementById("assignDeliveryButton");let candidateTimer=null,candidateRequest=0;
 const riderTabs=[...document.querySelectorAll("[data-rider-panel]")],riderPanels=[...document.querySelectorAll("[data-rider-view]")];riderTabs.forEach(tab=>tab.addEventListener("click",()=>{riderTabs.forEach(item=>item.classList.toggle("active",item===tab));riderPanels.forEach(panel=>panel.hidden=panel.dataset.riderView!==tab.dataset.riderPanel);document.querySelector(".admin-view-stack")?.scrollTo?.({top:0});}));
 const flash=(text,type="success")=>message.innerHTML=`<div class="alert alert-${type}">${safe(text)}</div>`;
 const distance=r=>r.distanceToShopKm===null?(r.locationFresh?"Shop location unavailable":"Location unavailable"):`${Number(r.distanceToShopKm).toFixed(1)} km away`;
 const loadApplications=async()=>{try{const{data}=await API.get("/admin/riders/applications",auth()),applications=data.applications||[],pending=applications.filter(a=>!["approved","rejected"].includes(a.applicationStatus)).length;const stat=document.getElementById("riderStatApplications");if(stat)stat.textContent=pending;applicationRows.innerHTML=applications.map(a=>`<tr><td><strong>${safe(a.fullName)}</strong><br><small>${safe(a.phone)}</small></td><td>${safe(a.vehicleType)}<br><small>${safe(a.plateNumber)}</small></td><td>${safe(a.email)}</td><td>${safe(a.inspectionStatus)}</td><td>${safe(a.applicationStatus)}</td><td><button class="btn btn-sm btn-dark review-application" data-id="${a.id}">Review</button></td></tr>`).join("")||'<tr><td colspan="6">No rider applications yet.</td></tr>';document.querySelectorAll(".review-application").forEach(b=>b.onclick=()=>openApplication(b.dataset.id));}catch(error){applicationRows.innerHTML=`<tr><td colspan="6" class="text-danger">${safe(error.response?.data?.message||"Unable to load applications.")}</td></tr>`;}};
 const openApplication=async id=>{try{const a=(await API.get(`/admin/riders/applications/${id}`,auth())).data.application;review.innerHTML=`<div class="rider-review-overlay" role="dialog" aria-modal="true" aria-labelledby="riderReviewTitle"><div class="rider-review-dialog"><header class="rider-review-header"><div><span class="admin-eyebrow">Rider screening</span><h3 id="riderReviewTitle">${safe(a.fullName)}</h3><p>${safe(a.email)} · ${safe(a.phone)}<br>${safe(a.vehicleType)} · ${safe(a.plateNumber)}</p></div><button class="btn-close" id="closeReview" aria-label="Close review"></button></header><div class="rider-review-body">${a.documentWarning?`<div class="alert alert-warning">A stored document could not be opened: ${safe(a.documentWarning)}. Ask the rider to submit that document again.</div>`:""}<section class="rider-document-grid"><article><i class="bi bi-file-earmark-check"></i><div><strong>Proof of ownership</strong><small>Required document</small></div>${a.ownershipDocumentUrl?`<a class="btn btn-outline-light" href="${safe(a.ownershipDocumentUrl)}" target="_blank" rel="noopener">Open document</a>`:`<span class="badge text-bg-danger">Unavailable</span>`}</article><article><i class="bi bi-person-vcard"></i><div><strong>Driving licence</strong><small>When applicable</small></div>${a.drivingLicenseUrl?`<a class="btn btn-outline-light" href="${safe(a.drivingLicenseUrl)}" target="_blank" rel="noopener">Open document</a>`:`<span class="badge text-bg-secondary">Not supplied</span>`}</article></section><label class="form-label" for="decisionNotes">Admin review note</label><textarea id="decisionNotes" class="form-control" rows="4" placeholder="Reason or review note">${safe(a.inspectionNotes||"")}</textarea><div class="alert alert-info mt-3"><strong>Pass rider</strong> creates a username and temporary password automatically and sends them to ${safe(a.email)}.</div></div><footer class="rider-review-actions"><button id="rejectApplication" class="btn btn-outline-danger">Fail rider</button><button id="approveApplication" class="btn btn-success">Pass rider, create login &amp; email</button></footer></div></div>`;
 document.getElementById("closeReview").onclick=()=>review.innerHTML="";document.getElementById("approveApplication").onclick=async event=>{event.currentTarget.disabled=true;try{const result=(await API.post(`/admin/riders/applications/${id}/approve`,{notes:document.getElementById("decisionNotes").value},auth())).data;flash(`${result.message} Username: ${result.credentials.username}. Temporary password: ${result.credentials.temporaryPassword}.`,result.emailSent?"success":"warning");review.innerHTML="";await load();}catch(error){flash(error.response?.data?.message||"Unable to approve rider.","danger");event.currentTarget.disabled=false;}};document.getElementById("rejectApplication").onclick=async()=>{const notes=document.getElementById("decisionNotes").value||window.prompt("Reason the rider failed:")||"";await API.post(`/admin/riders/applications/${id}/reject`,{notes},auth());flash("Rider application marked as failed.","warning");review.innerHTML="";await loadApplications();};}catch(error){flash(error.response?.data?.message||"Unable to open application.","danger");}};
 const load=async()=>{await loadApplications();try{const{data}=await API.get("/admin/riders",auth()),riders=data.riders||[],active=riders.filter(r=>r.accountStatus==="active"),eligible=active.filter(r=>r.availabilityStatus==="available"),busy=active.filter(r=>r.availabilityStatus==="busy");[["riderStatActive",active.length],["riderStatAvailable",eligible.length],["riderStatBusy",busy.length]].forEach(([id,value])=>{const node=document.getElementById(id);if(node)node.textContent=value;});rows.innerHTML=riders.map((r,index)=>`<tr><td><strong>${safe(r.fullName)}</strong><br><small>${safe(r.username||r.phone)}</small></td><td>${safe(r.vehicleType||"—")}<br><small>${safe(r.vehicleRegistrationNumber||"")}</small></td><td><span class="badge text-bg-${r.availabilityStatus==="available"?"success":r.availabilityStatus==="busy"?"warning":"secondary"}">${safe(r.availabilityStatus)}</span></td><td>${index===0&&r.distanceToShopKm!==null?'<span class="badge text-bg-success me-1">Nearest</span>':""}${safe(distance(r))}</td><td>${r.successfulDeliveries}/${r.totalDeliveries}</td><td>₦${Number(r.totalEarnings||0).toLocaleString()}</td><td><button class="btn btn-sm btn-outline-${r.accountStatus==="active"?"danger":"success"} rider-status" data-id="${r.id}" data-status="${r.accountStatus==="active"?"inactive":"active"}">${r.accountStatus==="active"?"Suspend":"Activate"}</button></td></tr>`).join("")||'<tr><td colspan="7">No riders onboarded yet.</td></tr>';document.querySelectorAll(".rider-status").forEach(button=>button.onclick=async()=>{await API.patch(`/admin/riders/${button.dataset.id}/status`,{accountStatus:button.dataset.status},auth());await load();});}catch(error){rows.innerHTML=`<tr><td colspan="7" class="text-danger">${safe(error.response?.data?.message||"Unable to load riders.")}</td></tr>`;}};
 const resetCandidates=(text="Enter the customer order number to load available riders.",tone="")=>{candidateRequest+=1;candidateBlock.hidden=true;select.disabled=true;assignButton.disabled=true;select.innerHTML='<option value="">Select an available rider</option>';orderFeedback.className=`rider-assignment-feedback${tone?` ${tone}`:""}`;orderFeedback.textContent=text;};
 const loadCandidates=async()=>{const orderId=Number(orderInput.value),request=++candidateRequest;if(!Number.isInteger(orderId)||orderId<1)return resetCandidates();candidateBlock.hidden=true;select.disabled=true;assignButton.disabled=true;orderFeedback.className="rider-assignment-feedback loading";orderFeedback.textContent=`Checking order #${orderId} and finding available riders…`;try{const{data}=await API.get(`/admin/riders/assignment-candidates/${orderId}`,auth());if(request!==candidateRequest)return;const candidates=data.candidates||[];orderFeedback.className=`rider-assignment-feedback ${candidates.length?"ready":"warning"}`;orderFeedback.innerHTML=`<strong>Order #${data.order.id}</strong> · ${safe(data.order.customerName||"Customer")}<br><span>${safe(data.order.deliveryAddress||"Delivery address unavailable")}</span>`;candidateBlock.hidden=false;if(!candidates.length){select.innerHTML='<option value="">No available riders right now</option>';select.disabled=true;assignButton.disabled=true;return;}select.innerHTML='<option value="">Select an available rider</option>'+candidates.map((r,index)=>`<option value="${r.id}">${index===0&&r.distanceToShopKm!==null?"Closest — ":""}${safe(r.fullName)} — ${r.distanceToShopKm===null?"GPS distance unavailable":`${Number(r.distanceToShopKm).toFixed(1)} km from pickup`}</option>`).join("");select.disabled=false;assignButton.disabled=true;}catch(error){if(request!==candidateRequest)return;resetCandidates(error.response?.data?.message||"Unable to load available riders.","danger");}};
 orderInput?.addEventListener("input",()=>{clearTimeout(candidateTimer);resetCandidates("Checking the order…","loading");candidateTimer=setTimeout(loadCandidates,450);});
 select?.addEventListener("change",()=>{assignButton.disabled=!select.value;});
 form?.addEventListener("submit",async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));assignButton.disabled=true;try{await API.post(`/admin/riders/assign/${values.orderId}`,{riderId:Number(values.riderId)},auth());flash(`Order #${values.orderId} assigned successfully. Use the Live Tracking workspace to monitor the rider.`);form.reset();resetCandidates();await load();}catch(error){flash(error.response?.data?.message||"Unable to assign delivery.","danger");assignButton.disabled=!select.value;}});document.getElementById("refreshRiders")?.addEventListener("click",load);window.addEventListener("nutridust:admin-refresh",event=>{if(event.detail?.view==="riders")load();});await load();
}
