import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./rider.css";
import "./rider-commerce.css";
import "./rider-mobile.css";
import axios from "axios";

const API=axios.create({baseURL:__API_URL__});
const TOKEN_KEY="nutridust-rider-token";
const app=document.getElementById("rider-app");
let state={rider:null,deliveries:[],notifications:[],commerce:null,tab:"jobs"};
const escape=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const money=value=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(value||0));
const date=value=>value?new Intl.DateTimeFormat("en-NG",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
API.interceptors.request.use(config=>{const token=localStorage.getItem(TOKEN_KEY);if(token)config.headers.Authorization=`Bearer ${token}`;return config;});
API.interceptors.response.use(response=>response,error=>{if(error.response?.status===401){localStorage.removeItem(TOKEN_KEY);renderLogin();}return Promise.reject(error);});

function renderLogin(){
    clearInterval(dashboardTimer);
    clearInterval(locationTimer);
    dashboardTimer=null;
    locationTimer=null;
    state={rider:null,deliveries:[],notifications:[],commerce:null,tab:"jobs"};
    app.innerHTML=`<main class="rider-login"><section class="login-panel"><div class="brand-mark"><i class="bi bi-bicycle"></i></div><p class="eyebrow">NutriDust Logistics</p><h1>Welcome back, rider.</h1><p class="text-secondary mb-4">Sign in after NutriDust has inspected and approved your bike.</p><form id="rider-login"><label class="form-label">Username, phone or email</label><input class="form-control form-control-lg mb-3" name="login" autocomplete="username" required><label class="form-label">Password</label><input class="form-control form-control-lg mb-3" name="password" type="password" autocomplete="current-password" required minlength="8"><div id="login-error" class="alert alert-danger d-none"></div><button class="btn btn-success btn-lg w-100" type="submit"><span>Sign in</span></button></form><div class="d-flex justify-content-between mt-3"><button class="btn btn-link p-0" id="apply-rider">Apply as a rider</button><button class="btn btn-link p-0" id="forgot-password">Forgot password?</button></div></section></main>`;
    document.getElementById("rider-login").addEventListener("submit",login);
    document.getElementById("apply-rider").onclick=renderApplication;
    document.getElementById("forgot-password").onclick=renderForgotPassword;
}
async function login(event){event.preventDefault();const button=event.currentTarget.querySelector("button"),box=document.getElementById("login-error");button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Signing in';box.classList.add("d-none");try{const{data}=await API.post("/rider/login",Object.fromEntries(new FormData(event.currentTarget)));localStorage.setItem(TOKEN_KEY,data.token);if(data.rider.mustChangePassword)return renderChangePassword(true);await loadDashboard();}catch(error){box.textContent=error.response?.data?.message||"Unable to sign in. Check your connection.";box.classList.remove("d-none");button.disabled=false;button.innerHTML="<span>Sign in</span>";}}

function renderApplication(){app.innerHTML=`<main class="rider-login"><section class="login-panel" style="max-width:720px"><button class="btn btn-link p-0 mb-3" id="back-login">← Sign in</button><h1>Apply to become a rider</h1><p class="text-secondary">Your phone and email can only be registered once. We inspect your bike before approval.</p><form id="rider-application" class="row g-3"><div class="col-md-4"><input class="form-control" name="firstName" placeholder="First name" required></div><div class="col-md-4"><input class="form-control" name="middleName" placeholder="Middle name"></div><div class="col-md-4"><input class="form-control" name="surname" placeholder="Surname" required></div><div class="col-md-6"><input class="form-control" name="phone" type="tel" placeholder="Phone number" required></div><div class="col-md-6"><input class="form-control" name="email" type="email" placeholder="Email for activation" required></div><div class="col-md-6"><select class="form-select" name="vehicleType"><option>Motorcycle</option><option>Bicycle</option><option>Car</option><option>Van</option></select></div><div class="col-md-6"><input class="form-control" name="plateNumber" placeholder="Plate number" required></div><div class="col-md-6"><label class="form-label">Proof of ownership (required)</label><input class="form-control" name="ownershipDocument" type="file" accept=".pdf,image/*" required></div><div class="col-md-6"><label class="form-label">Driving licence (if applicable)</label><input class="form-control" name="drivingLicense" type="file" accept=".pdf,image/*"></div><div id="application-message"></div><div class="col-12"><button class="btn btn-success btn-lg w-100">Submit application</button></div></form></section></main>`;document.getElementById("back-login").onclick=renderLogin;document.getElementById("rider-application").onsubmit=async e=>{e.preventDefault();const box=document.getElementById("application-message"),button=e.currentTarget.querySelector("button");button.disabled=true;try{const{data}=await API.post("/rider/applications",new FormData(e.currentTarget));box.innerHTML=`<div class="alert alert-success">${escape(data.message)} Reference: <strong>${escape(data.trackingCode)}</strong>.</div>`;e.currentTarget.reset();}catch(error){box.innerHTML=`<div class="alert alert-danger">${escape(error.response?.data?.message||"Unable to submit application.")}</div>`;}finally{button.disabled=false;}};}
function renderForgotPassword(){app.innerHTML=`<main class="rider-login"><section class="login-panel"><button class="btn btn-link p-0 mb-3" id="back-login">← Sign in</button><h1>Reset password</h1><form id="forgot-form"><input class="form-control mb-3" name="login" placeholder="Username, phone or email" required><div id="reset-message"></div><button class="btn btn-success w-100">Send reset link</button></form></section></main>`;document.getElementById("back-login").onclick=renderLogin;document.getElementById("forgot-form").onsubmit=async e=>{e.preventDefault();const{data}=await API.post("/rider/password/forgot",Object.fromEntries(new FormData(e.currentTarget)));document.getElementById("reset-message").innerHTML=`<div class="alert alert-info">${escape(data.message)}</div>`;};}
function renderResetPassword(token){app.innerHTML=`<main class="rider-login"><section class="login-panel"><h1>Choose a new password</h1><form id="reset-form"><input class="form-control mb-3" name="newPassword" type="password" minlength="8" placeholder="At least 8 characters" required><div id="reset-message"></div><button class="btn btn-success w-100">Reset password</button></form></section></main>`;document.getElementById("reset-form").onsubmit=async e=>{e.preventDefault();try{const{data}=await API.post("/rider/password/reset",{token,newPassword:new FormData(e.currentTarget).get("newPassword")});history.replaceState({},"",location.pathname);window.alert(data.message);renderLogin();}catch(error){document.getElementById("reset-message").innerHTML=`<div class="alert alert-danger">${escape(error.response?.data?.message||"Unable to reset password.")}</div>`;}};}
function renderChangePassword(required=false){app.innerHTML=`<main class="rider-login"><section class="login-panel"><h1>${required?"Secure your account":"Change password"}</h1><p>${required?"Replace your temporary password before continuing.":"Enter your current and new password."}</p><form id="change-form">${required?"":'<input class="form-control mb-3" name="currentPassword" type="password" placeholder="Current password" required>'}<input class="form-control mb-3" name="newPassword" type="password" minlength="8" placeholder="New password (at least 8 characters)" required><div id="change-message"></div><button class="btn btn-success w-100">Save password</button></form></section></main>`;document.getElementById("change-form").onsubmit=async e=>{e.preventDefault();try{await API.post("/rider/password/change",Object.fromEntries(new FormData(e.currentTarget)));await loadDashboard();}catch(error){document.getElementById("change-message").innerHTML=`<div class="alert alert-danger">${escape(error.response?.data?.message||"Unable to change password.")}</div>`;}};}

const activeStatuses=new Set(["assigned","accepted","picked_up","out_for_delivery"]);
function stats(){const active=state.deliveries.filter(d=>activeStatuses.has(d.deliveryStatus)).length,done=state.deliveries.filter(d=>d.deliveryStatus==="delivered").length;return `<div class="stats-grid"><article><span>Active jobs</span><strong>${active}</strong></article><article><span>Completed</span><strong>${done}</strong></article><article><span>Wallet</span><strong>${money(state.rider.walletBalance)}</strong></article></div>`;}
function statusLabel(value){return String(value||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
function nextAction(d){return {assigned:["accepted","Accept delivery","success"],accepted:["picked_up","Confirm pickup","primary"],picked_up:["out_for_delivery","Start delivery","warning"],out_for_delivery:["delivered","Complete delivery","success"]}[d.deliveryStatus];}
function deliveryCard(d){const action=nextAction(d),destination=encodeURIComponent(d.deliveryAddress);return `<article class="delivery-card" data-id="${d.id}"><div class="d-flex justify-content-between gap-3"><div><span class="order-number">ORDER #${d.orderId}</span><h3>${escape(d.customerName)}</h3></div><span class="status-pill status-${escape(d.deliveryStatus)}">${escape(statusLabel(d.deliveryStatus))}</span></div><div class="address"><i class="bi bi-geo-alt-fill"></i><span>${escape(d.deliveryAddress)}</span></div><div class="rider-navigation"><a class="btn btn-outline-dark" href="https://www.google.com/maps/dir/?api=1&destination=${destination}" target="_blank" rel="noopener"><i class="bi bi-map me-1"></i>Google</a><a class="btn btn-primary" href="https://www.waze.com/ul?q=${destination}&navigate=yes" target="_blank" rel="noopener"><i class="bi bi-navigation-fill me-1"></i>Waze</a></div><div class="delivery-meta"><span><i class="bi bi-box-seam"></i>${d.items.length} item(s)</span><span><i class="bi bi-cash"></i>${money(d.deliveryFee)}</span><span><i class="bi bi-clock"></i>${date(d.assignedAt)}</span></div><div class="delivery-actions"><a class="btn btn-outline-dark" href="tel:${encodeURIComponent(d.customerPhone)}"><i class="bi bi-telephone"></i> Call</a><button class="btn btn-outline-danger fail-job" ${["delivered","failed"].includes(d.deliveryStatus)?"disabled":""}>Report issue</button>${action?`<button class="btn btn-${action[2]} advance-job" data-status="${action[0]}">${action[1]}</button>`:""}</div></article>`;}
function jobsView(){const active=state.deliveries.filter(d=>activeStatuses.has(d.deliveryStatus)),history=state.deliveries.filter(d=>!activeStatuses.has(d.deliveryStatus));return `<section class="content-panel"><div class="section-heading"><div><p class="eyebrow">Today</p><h2>Your deliveries</h2></div><button class="btn btn-light" id="refresh"><i class="bi bi-arrow-clockwise"></i></button></div><div class="job-list">${active.map(deliveryCard).join("")||'<div class="empty-state"><i class="bi bi-check-circle"></i><h3>You are all caught up</h3><p>New assigned deliveries will appear here.</p></div>'}</div>${history.length?`<h2 class="h5 mt-5">Recent history</h2><div class="job-list compact">${history.slice(0,10).map(deliveryCard).join("")}</div>`:""}</section>`;}
function earningsView(){const c=state.commerce;return `<section class="content-panel"><p class="eyebrow">Your money</p><h2>Earnings &amp; benefits</h2><div class="wallet-card"><span>Available balance</span><strong>${money(state.rider.walletBalance)}</strong><small>Total earned: ${money(state.rider.totalEarnings)}</small></div><div id="earning-list" class="mt-4"><p class="text-secondary">Loading transactions…</p></div><hr class="my-4"><h3 class="h5">Withdraw earnings</h3><form id="withdrawal-form" class="row g-2"><div class="col-sm-6"><input class="form-control" name="amount" type="number" min="1000" placeholder="Amount (₦)" required></div><div class="col-sm-6"><input class="form-control" name="bankName" placeholder="Bank name" required></div><div class="col-sm-6"><input class="form-control" name="accountName" placeholder="Account name" required></div><div class="col-sm-6"><input class="form-control" name="accountNumber" inputmode="numeric" minlength="10" placeholder="Account number" required></div><div class="col-12"><button class="btn btn-success">Request withdrawal</button></div></form><hr class="my-4"><div class="benefit-grid"><article><span class="eyebrow">Subscription</span><h3>${escape(c?.subscription?.planName||"No active plan")}</h3><p>${c?.subscription?`Expires ${date(c.subscription.expiresAt)}`:"Choose a plan to activate rider benefits."}</p><div>${(c?.plans||[]).map(p=>`<button class="btn btn-sm btn-outline-success activate-plan" data-id="${p.id}">${escape(p.name)} · ${money(p.price)}</button>`).join(" ")}</div></article><article><span class="eyebrow">Refer a rider</span><h3>${escape(c?.referralCode||"Loading…")}</h3><p>Share this code. Rewards unlock after their first delivery.</p><form id="referral-form" class="input-group"><input class="form-control" name="code" placeholder="Apply a referral code"><button class="btn btn-outline-dark">Apply</button></form></article></div><div id="commerce-message" class="mt-3"></div></section>`;}
function notificationsView(){return `<section class="content-panel"><div class="section-heading"><div><p class="eyebrow">Updates</p><h2>Notifications</h2></div><button class="btn btn-light" id="read-all">Mark all read</button></div><div class="notification-list">${state.notifications.map(n=>`<article class="notification ${n.readAt?"":"unread"}"><i class="bi bi-bell-fill"></i><div><strong>${escape(n.title)}</strong><p>${escape(n.message)}</p><small>${date(n.createdAt)}</small></div></article>`).join("")||'<div class="empty-state"><i class="bi bi-bell"></i><h3>No notifications yet</h3></div>'}</div></section>`;}
function profileView(){const r=state.rider;return `<section class="content-panel"><p class="eyebrow">Account</p><h2>${escape(r.fullName)}</h2><div class="profile-card"><div class="profile-icon">${escape(r.fullName?.[0]||"R")}</div><dl><div><dt>Username</dt><dd>${escape(r.username||"—")}</dd></div><div><dt>Phone</dt><dd>${escape(r.phone)}</dd></div><div><dt>Email</dt><dd>${escape(r.email||"Not supplied")}</dd></div><div><dt>Vehicle</dt><dd>${escape(r.vehicleType||"Not supplied")}</dd></div><div><dt>Registration</dt><dd>${escape(r.vehicleRegistrationNumber||"Not supplied")}</dd></div></dl><div class="d-flex gap-2"><button class="btn btn-outline-dark" id="change-rider-password">Change password</button><button class="btn btn-outline-danger" id="logout"><i class="bi bi-box-arrow-right"></i> Sign out</button></div></div></section>`;}
function shell(){const views={jobs:jobsView,earnings:earningsView,notifications:notificationsView,profile:profileView};app.innerHTML=`<div class="rider-shell"><header class="rider-header"><div><p class="eyebrow">Good day</p><h1>${escape(state.rider.fullName?.split(" ")[0])}</h1></div><label class="availability"><span>${escape(statusLabel(state.rider.availabilityStatus))}</span><input id="availability" type="checkbox" ${state.rider.availabilityStatus!=="offline"?"checked":""}></label></header>${stats()}${views[state.tab]()}<nav class="bottom-nav">${[["jobs","house-door","Jobs"],["earnings","wallet2","Earnings"],["notifications","bell","Alerts"],["profile","person","Profile"]].map(([tab,icon,label])=>`<button data-tab="${tab}" class="${state.tab===tab?"active":""}"><i class="bi bi-${icon}"></i><span>${label}</span></button>`).join("")}</nav></div>`;bind();}
function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=async()=>{state.tab=b.dataset.tab;if(state.tab==="earnings")await loadCommerce();shell();if(state.tab==="earnings")loadEarnings();});document.getElementById("refresh")?.addEventListener("click",loadDashboard);document.getElementById("logout")?.addEventListener("click",()=>{localStorage.removeItem(TOKEN_KEY);renderLogin();});document.getElementById("availability")?.addEventListener("change",updateAvailability);document.getElementById("read-all")?.addEventListener("click",async()=>{await API.patch("/rider/notifications/read");state.notifications.forEach(n=>n.readAt=new Date().toISOString());shell();});document.querySelectorAll(".advance-job").forEach(b=>b.onclick=()=>changeStatus(b.closest(".delivery-card").dataset.id,b.dataset.status));document.querySelectorAll(".fail-job").forEach(b=>b.onclick=()=>{const note=window.prompt("What went wrong? Please provide a reason.");if(note)changeStatus(b.closest(".delivery-card").dataset.id,"failed",note);});document.getElementById("withdrawal-form")?.addEventListener("submit",submitWithdrawal);document.getElementById("referral-form")?.addEventListener("submit",applyReferral);document.querySelectorAll(".activate-plan").forEach(b=>b.onclick=()=>activatePlan(b.dataset.id));}
async function changeStatus(id,status,note=""){if(status==="delivered"&&!window.confirm("Confirm that this order has been delivered?"))return;try{await API.patch(`/rider/deliveries/${id}/status`,{status,note});await loadDashboard();}catch(error){window.alert(error.response?.data?.message||"Unable to update this delivery.");}}
async function updateAvailability(event){try{const{data}=await API.patch("/rider/availability",{status:event.target.checked?"available":"offline"});state.rider.availabilityStatus=data.availabilityStatus;shell();}catch(error){event.target.checked=!event.target.checked;window.alert(error.response?.data?.message||"Unable to change availability.");}}
async function loadEarnings(){try{const{data}=await API.get("/rider/earnings");const box=document.getElementById("earning-list");if(box)box.innerHTML=data.entries.map(e=>`<article class="earning-row"><div><strong>${escape(e.description)}</strong><small>${date(e.createdAt)}</small></div><b>+${money(e.amount)}</b></article>`).join("")||'<div class="empty-state"><p>No earnings recorded yet.</p></div>';}catch{}}
async function loadCommerce(){try{state.commerce=(await API.get("/rider/commerce")).data;}catch{state.commerce=null;}}
function commerceMessage(message,type="success"){const box=document.getElementById("commerce-message");if(box)box.innerHTML=`<div class="alert alert-${type}">${escape(message)}</div>`;}
async function submitWithdrawal(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));try{await API.post("/rider/withdrawals",data);commerceMessage("Withdrawal request submitted for review.");await loadDashboard();}catch(error){commerceMessage(error.response?.data?.message||"Unable to request withdrawal.","danger");}}
async function applyReferral(event){event.preventDefault();try{const{data}=await API.post("/rider/referrals/apply",Object.fromEntries(new FormData(event.currentTarget)));commerceMessage(data.message);await loadCommerce();}catch(error){commerceMessage(error.response?.data?.message||"Unable to apply referral.","danger");}}
async function activatePlan(planId){try{await API.post("/rider/subscriptions",{planId:Number(planId)});await loadCommerce();shell();loadEarnings();}catch(error){commerceMessage(error.response?.data?.message||"Unable to activate plan.","danger");}}
async function shareLocation(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(position=>{const active=state.deliveries.find(d=>activeStatuses.has(d.deliveryStatus));API.post("/rider/location",{latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,deliveryId:active?.id}).catch(()=>{});},()=>{},{enableHighAccuracy:true,maximumAge:60000,timeout:10000});}
let dashboardSignature="";
async function loadDashboard(){try{const{data}=await API.get("/rider/dashboard"),next={rider:data.rider,deliveries:data.deliveries||[],notifications:data.notifications||[]},signature=JSON.stringify(next);state={...state,...next};if(signature!==dashboardSignature){dashboardSignature=signature;shell();enableBrowserNotifications();}startActiveLocationSharing();}catch(error){if(error.response?.status!==401){app.innerHTML='<div class="empty-state full"><h2>We could not load your dashboard</h2><button class="btn btn-success" id="retry">Try again</button></div>';document.getElementById("retry").onclick=loadDashboard;}}}
let locationTimer,dashboardTimer,locationIntervalMs=null;
function startActiveLocationSharing(){const active=state.deliveries.some(d=>activeStatuses.has(d.deliveryStatus)),nextInterval=active?15000:60000;if(state.rider?.availabilityStatus==="offline"){clearInterval(locationTimer);locationTimer=null;locationIntervalMs=null;}else if(!locationTimer||locationIntervalMs!==nextInterval){clearInterval(locationTimer);locationIntervalMs=nextInterval;shareLocation();locationTimer=setInterval(shareLocation,nextInterval);}if(!dashboardTimer)dashboardTimer=setInterval(()=>{if(!document.hidden)loadDashboard();},3000);}
async function enableBrowserNotifications(){if(!("Notification" in window)||Notification.permission==="denied")return;if(Notification.permission==="default")await Notification.requestPermission();if(Notification.permission==="granted"){const unread=state.notifications.find(n=>!n.readAt);if(unread&&!sessionStorage.getItem(`notice-${unread.id}`)){new Notification(unread.title,{body:unread.message});sessionStorage.setItem(`notice-${unread.id}`,"1");}}}
app.addEventListener("click",event=>{if(event.target.closest("#change-rider-password"))renderChangePassword(false);});
const query=new URLSearchParams(location.search),verifyToken=query.get("verify"),resetToken=query.get("reset");
if(verifyToken){API.post("/rider/applications/verify",{token:verifyToken}).then(({data})=>{history.replaceState({},"",location.pathname);window.alert(data.message);renderLogin();}).catch(error=>{window.alert(error.response?.data?.message||"Unable to verify application.");renderLogin();});}else if(resetToken)renderResetPassword(resetToken);else localStorage.getItem(TOKEN_KEY)?loadDashboard():renderLogin();
